### ISSUE TITLE
Easiest way to update to newest outline version?

### ISSUE THREAD

**Issue by tenneck** [chsasank/outline-wiki-docker-compose#11]
Hi guys,
this is not an issue, more like a best practice question. Which way would you recommend to update to the newest outline version without losing data?
Thanks.

**Comment by Snuupy** [comment]
I did the following:

```
docker-compose pull
docker-compose down && docker-compose up -d
```

and it seems to work.

I think that if you run `make install` again it'll rewrite some variables and it'll rerun the install script ([which you don't want](https://github.com/chsasank/outline-wiki-docker-compose/blob/master/help.md))

**Comment by tenneck** [comment]
Thanks, that worked for me as well!

**Comment by Snuupy** [comment]
Update: worked for 0.53.1 for me today, looks like db migrations went just fine :)

**Comment by Snuupy** [comment]
I'm having some issues with upgrading from 0.53.1 -> 0.54 due to the node build/server/scripts/20210226232041-migrate-authentication.js script that needs to be run.

```
outline_1   | $ node ./build/server/scripts/20210226232041-migrate-authentication.js
outline_1   |
outline_1   | error Command failed with exit code 1.
```

**Comment by Snuupy** [comment]
To get this working, edit the docker-compose file.

Change the line that says: 

```
command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
```

to:

```
command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && node build/server/scripts/20210226232041-migrate-authentication.js && yarn start"
```

you can change it back after the migration has completed.
