### ISSUE TITLE
Sending eMail invites

### ISSUE THREAD

**Issue by awoehrl** [chsasank/outline-wiki-docker-compose#12]
Thanks, this works really well. The only thing that doesn't seem to work is the sending of invites and signing up with an eMail address. Is there anything I can do to make it work?

**Comment by dmezh** [comment]
^also experiencing this

**Comment by dmezh** [comment]
> I have it working with SendGrid, but only for invites - the email signup doesn't seem to work and no error is thrown by Outline.

Update: Use a decent SMTP server 😅 

Outline is hardcoded to use secure SMTP when in production mode. If you want to change that, you can make that change [here](https://github.com/outline/outline/blob/de6ee91d9636300d3cc8be5db490ce27a2e0b24e/server/mailer.js#L166) (change to secure: false) and rebuild the docker image.

I also needed to add legacy TLS 1.0 support: `tls: { secureProtocol: "TLSv1_method" },` in that same block.

**Comment by chsasank** [comment]
@kevalnagda wrote a nice tutorial on this: https://kevalnagda.github.io/sendgrid-with-outline
