### ISSUE TITLE
env.outline is malformed after running setup script

### ISSUE THREAD

**Issue by jdan** [chsasank/outline-wiki-docker-compose#13]
Hi! Thanks for this - it let me try out outline in no time at all.

Wanted to file a lil bug for something a friend and I both caught independently. After going through `make install` I was receiving a 502 error. The logs mentioned something along the lines of: "Validation isIn on language failed." Curious, I poked around some of the env files and noticed the following at the bottom of `env.outline`

```
DEFAULT_LANGUAGE=en_USHOST=outline.jordanscales.com
```

(No space after `en_US`, which seemed relevant to "isIn on language failed"). Adding a newline to change the text to:

```
DEFAULT_LANGUAGE=en_US
HOST=outline.jordanscales.com
```

Fixed the issue on restart.

**Comment by chsasank** [comment]
May be something to do with bash/sed? Or may be linux/windows thingy?

**Comment by narzero** [comment]
Experienced the same issue...

Ubuntu 20.04
Docker version 20.10.2, build 2291f61

**Comment by 6uhrmittag** [comment]
Same. This is because the `.env.sample` doesn't end with a newline. 

These variables use `env_add` - no `sed` involed, just `echo`.

````cls
cd /tmp
wget https://raw.githubusercontent.com/outline/outline/develop/.env.sample
echo "HOST" >> .env.sample
cat .env.sample
````
result:
````txt
# Custom logo that displays on the authentication screen, scaled to height: 60px
# TEAM_LOGO=https://example.com/images/logo.png

DEFAULT_LANGUAGE=en_USHOST
````

Simples fix is to just add an empty newline to https://raw.githubusercontent.com/outline/outline/develop/.env.sample
