### ISSUE TITLE
/outline command

### ISSUE THREAD

**Issue by Bmiest** [chsasank/outline-wiki-docker-compose#15]
When I add the slack integration, it does not add the /outline command to my slack env.
Do we need to add a /outline command in https://api.slack.com/apps for /outline? What call do we have to use?

**Comment by chsasank** [comment]
Yes, you have to edit slack config. Some instructions are here: https://github.com/outline/outline/issues/730#issuecomment-421534291

**Comment by Bmiest** [comment]
@chsasank thanks, I'll take a look
