### ISSUE TITLE
Profile's photo don't show

### ISSUE THREAD

**Issue by wildsonc** [chsasank/outline-wiki-docker-compose#21]
How to fix that?
![image](https://user-images.githubusercontent.com/72408418/120346858-24211280-c2d2-11eb-84c8-cf281b630994.png)
Just as profile pictures are in error, I'm using miniO

**Comment by aldidoanta** [comment]
@wildsonc possibly related issue: https://github.com/chsasank/outline-wiki-docker-compose/issues/10

I had a similar issue, and posted my solution here  https://github.com/chsasank/outline-wiki-docker-compose/issues/10#issuecomment-848697901

**Comment by wildsonc** [comment]
@aldidoanta Thanks
