### ISSUE TITLE
SSL Cert for 'not' localhost

### ISSUE THREAD

**Issue by matthiscock** [chsasank/outline-wiki-docker-compose#23]
Can your script be editted to allow for HTTPS for a server which is not localhost?

This would allow it to be made secure for those installs which are not localhost driven

Currently using this on a Digital Ocean Droplet

**Comment by chsasank** [comment]
Yes, just replce the generated certs with *your* certs/pems and you're good to go.

**Comment by chsasank** [comment]
Also refer to #1
