### ISSUE TITLE
Used ouline docker compose as is. Getting wss error. Not able to edit document. 

### ISSUE THREAD

**Issue by krishna0511** [chsasank/outline-wiki-docker-compose#38]
Any help is deeply appreciated.
<img width="444" alt="Screenshot 2022-02-21 at 7 49 30 AM" src="https://user-images.githubusercontent.com/1832725/154879301-4ca508ef-f404-4e8e-a2fe-b60c3bf66e5e.png">

**Comment by eeshaan** [comment]
https://app.getoutline.com/share/770a97da-13e5-401e-9f8a-37949c19f97e/doc/nginx-6htaRboR57

**Comment by eeshaan** [comment]
https://github.com/chsasank/outline-wiki-docker-compose/issues/35
