### ISSUE TITLE
Integration with slack work for Auth. For posting updates to slack or search through slack. Slack integration complains redirect uri is wrong

### ISSUE THREAD

**Issue by krishna0511** [chsasank/outline-wiki-docker-compose#39]
<img width="535" alt="Screenshot 2022-02-21 at 8 01 06 AM" src="https://user-images.githubusercontent.com/1832725/154879454-03a6e42b-aec3-42e9-80c7-50e58c68d26a.png">

Any idea how to get past the error

**Comment by eeshaan** [comment]
add the URI to your Slack app under **OAuth & Permissions** → **Redirect URLs**.
