### ISSUE TITLE
Slack Redirect URL

### ISSUE THREAD

**Issue by dlbone** [chsasank/outline-wiki-docker-compose#4]
I have outline running on an EC2 on AWS and when I click "Continue with Slack" I get redirected to "http://localhost/auth/slack" which clearly isn't a valid URL. What am I supposed to add to the config on make?

Nevermind, I'm not a smart man. Add the URL of the hosted location, not literally "localhost"

**Comment by chsasank** [comment]
Well first thing to choose is hostname. Use your DNS/IP etc. I guess the prompt could be made better. Help me with this by raising a PR? You have to edit [this line](https://github.com/chsasank/outline-wiki-docker-compose/blob/master/generate_conf.sh#L66) 

![image](https://user-images.githubusercontent.com/9305875/89854910-c1c81b80-dbb2-11ea-84b7-1a3ddf33d7a7.png)

> Nevermind, I'm not a smart man. Add the URL of the hosted location, not literally "localhost"

Glad you've figured it out :)
