### ISSUE TITLE
The script is not working as expected

### ISSUE THREAD

**Issue by nguyenrom** [chsasank/outline-wiki-docker-compose#6]
I have tried your tutorial but the app is not working.

The page is blank:
![image](https://user-images.githubusercontent.com/7044465/92322859-2bc2cc00-f05e-11ea-86cb-e18c514cac3f.png)

I use AWS Lightsail, Ubuntu 18.04.

**Comment by chsasank** [comment]
Can you provide more details? Logs from server?

**Comment by nguyenrom** [comment]
> Can you provide more details? Logs from server?

Thank you for your quick reply, I send you:

Outline Docker
`docker logs aa4d4368ac39
yarn run v1.22.4
$ yarn clean && yarn build:webpack
$ rimraf dist
$ NODE_ENV=production webpack --config webpack.config.prod.js
Hash: b659f20e2cf03f8466cc
Version: webpack 4.44.1
Time: 15942ms
Built at: 09/06/2020 9:35:28 AM
                                      Asset       Size  Chunks                                Chunk Names
                  0.cf2711195eccdd8c1b59.js    283 KiB       0  [emitted] [immutable]  [big]
      0.cf2711195eccdd8c1b59.js.LICENSE.txt    1.9 KiB          [emitted]
              0.cf2711195eccdd8c1b59.js.map   1.12 MiB       0  [emitted] [dev]
                  1.bbbed9b9d7cb5d9f9630.js    329 KiB       1  [emitted] [immutable]  [big]
              1.bbbed9b9d7cb5d9f9630.js.map    306 KiB       1  [emitted] [dev]
                 10.4f4faf26eb4685da17b0.js   18.5 KiB      10  [emitted] [immutable]
             10.4f4faf26eb4685da17b0.js.map   65.8 KiB      10  [emitted] [dev]
                 11.a394c9280b198b9f9d2e.js   3.95 KiB      11  [emitted] [immutable]
             11.a394c9280b198b9f9d2e.js.map   4.12 KiB      11  [emitted] [dev]
                 12.2a5454fc7f46ffbb5ad6.js   24.2 KiB      12  [emitted] [immutable]
             12.2a5454fc7f46ffbb5ad6.js.map   58.4 KiB      12  [emitted] [dev]
                  5.109047f5d93b3fc05e79.js    678 KiB       5  [emitted] [immutable]  [big]
      5.109047f5d93b3fc05e79.js.LICENSE.txt  542 bytes          [emitted]
              5.109047f5d93b3fc05e79.js.map   2.75 MiB       5  [emitted] [dev]
                  6.acb7fccfefe802bcae2b.js   63.6 KiB       6  [emitted] [immutable]
              6.acb7fccfefe802bcae2b.js.map    222 KiB       6  [emitted] [dev]
                  7.4bcd2b724e10bfabeb5d.js   28.3 KiB       7  [emitted] [immutable]
              7.4bcd2b724e10bfabeb5d.js.map   37.1 KiB       7  [emitted] [dev]
                  8.d36de0790b45efc070ed.js    269 KiB       8  [emitted] [immutable]  [big]
              8.d36de0790b45efc070ed.js.map    256 KiB       8  [emitted] [dev]
                  9.14d28e7e945883b992d3.js    131 KiB       9  [emitted] [immutable]
              9.14d28e7e945883b992d3.js.map    135 KiB       9  [emitted] [dev]
                                 index.html   1.62 KiB          [emitted]
               main.3551abe2056c65c22219.js    231 KiB       2  [emitted] [immutable]         main
           main.3551abe2056c65c22219.js.map    173 KiB       2  [emitted] [dev]               main
                              manifest.json    2.1 KiB          [emitted]
            runtime.925442e3eb8cd7a388e0.js   3.08 KiB       3  [emitted] [immutable]         runtime
        runtime.925442e3eb8cd7a388e0.js.map   12.7 KiB       3  [emitted] [dev]               runtime
            vendors.d94211bf708efce3dad9.js    561 KiB       4  [emitted] [immutable]  [big]  vendors
vendors.d94211bf708efce3dad9.js.LICENSE.txt      2 KiB          [emitted]
        vendors.d94211bf708efce3dad9.js.map   1.75 MiB       4  [emitted] [dev]               vendors
Entrypoint main [big] = runtime.925442e3eb8cd7a388e0.js runtime.925442e3eb8cd7a388e0.js.map vendors.d94211bf708efce3dad9.js vendors.d94211bf708efce3dad9.js.map main.3551abe2056c65c22219.js main.3551abe2056c65c22219.js.map
[0] multi ./app/index 28 bytes {2} [built]
[/95S] ./app/models/Document.js 24.2 KiB {2} [built]
[/gcL] ./app/stores/GroupMembershipsStore.js 11.2 KiB {2} [built]
[0Jmh] ./shared/utils/getQueryVariable.js 366 bytes {7} {9} [built]
[1d8r] ./app/stores/CollectionGroupMembershipsStore.js 10.8 KiB {2} [built]
[1fUH] ./app/env.js 41 bytes {2} [built]
[69r1] ./app/stores/index.js 94 bytes {2} [built]
[8nc1] ./app/routes/authenticated.js + 62 modules 385 KiB {8} [built]
    | ./app/routes/authenticated.js 4.02 KiB [built]
    | ./app/scenes/Archive.js 4.65 KiB [built]
    | ./app/scenes/Search/index.js 53 bytes [built]
    | ./app/scenes/Collection.js 18.9 KiB [built]
    | ./app/scenes/Dashboard.js 6.16 KiB [built]
    | ./app/scenes/DocumentNew.js 6.57 KiB [built]
    | ./app/scenes/Drafts.js 5.19 KiB [built]
    | ./app/scenes/Starred.js 5.67 KiB [built]
    | ./app/scenes/Templates.js 5.67 KiB [built]
    | ./app/scenes/Trash.js 4.61 KiB [built]
    | ./app/scenes/CollectionEdit.js 12 KiB [built]
    | ./app/scenes/CollectionMembers/index.js 86 bytes [built]
    | ./app/menus/NewDocumentMenu.js 9.16 KiB [built]
    | ./app/scenes/Search/Search.js 23.2 KiB [built]
    | ./app/menus/CollectionMenu.js 13.9 KiB [built]
    |     + 48 hidden modules
[OEJt] ./app/scenes/Document/KeyedDocument.js + 27 modules 178 KiB {1} [built]
    | ./app/scenes/Document/KeyedDocument.js 4.92 KiB [built]
    | ./app/scenes/ErrorOffline.js 549 bytes [built]
    | ./app/utils/emoji.js 648 bytes [built]
    | ./app/menus/NewChildDocumentMenu.js 8.61 KiB [built]
    | ./app/menus/TemplatesMenu.js 6.53 KiB [built]
    | ./shared/utils/parseDocumentSlug.js 229 bytes [built]
    |     + 22 hidden modules
[Pg5L] ./app/stores/RootStore.js 3.22 KiB {2} [built]
[QLeJ] ./app/stores/UiStore.js 14.6 KiB {2} [built]
[qn6K] ./app/scenes/Login/index.js + 6 modules 24.2 KiB {7} [built]
    | ./app/scenes/Login/index.js 10.7 KiB [built]
    | ./app/scenes/Login/Notices.js 1.44 KiB [built]
    | ./app/scenes/Login/Service.js 9.13 KiB [built]
    |     + 4 hidden modules
[xATA] ./app/index.js + 9 modules 28.5 KiB {2} [built]
    | ./app/index.js 2.5 KiB [built]
    | ./app/routes/index.js 1.32 KiB [built]
    | ./shared/styles/globals.js 1.88 KiB [built]
    | ./shared/styles/theme.js 7.04 KiB [built]
    |     + 6 hidden modules
[xqIG] ./shared/utils/routeHelpers.js 1.75 KiB {2} [built]
[yLpj] (webpack)/buildin/global.js 472 bytes {4} [built]
    + 1058 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  0.cf2711195eccdd8c1b59.js (283 KiB)
  1.bbbed9b9d7cb5d9f9630.js (329 KiB)
  vendors.d94211bf708efce3dad9.js (561 KiB)
  5.109047f5d93b3fc05e79.js (678 KiB)
  8.d36de0790b45efc070ed.js (269 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (795 KiB)
      runtime.925442e3eb8cd7a388e0.js
      vendors.d94211bf708efce3dad9.js
      main.3551abe2056c65c22219.js

Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
    [la58] ./node_modules/html-webpack-plugin/lib/loader.js!./server/static/index.html 1.63 KiB {0} [built]
    [yLpj] (webpack)/buildin/global.js 472 bytes {0} [built]
        + 1 hidden module
Done in 18.19s.
yarn run v1.22.4
$ /opt/outline/node_modules/.bin/sequelize db:migrate

Sequelize CLI [Node: 12.18.3, CLI: 6.2.0, ORM: 6.3.4]

Loaded configuration file "server/config/database.json".
Using environment "development".
No migrations were executed, database schema was already up to date.
Done in 0.63s.
yarn run v1.22.4
$ NODE_ENV=production node index.js

Running Outline in production mode.

> Listening on http://localhost:3000

(node:134) UnhandledPromiseRejectionWarning: SequelizeConnectionError: The server does not support SSL connections
    at /opt/outline/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:188:20
    at Connection.connectingErrorHandler (/opt/outline/node_modules/pg/lib/client.js:213:14)
    at Connection.emit (events.js:315:20)
    at Connection.EventEmitter.emit (domain.js:483:12)
    at Socket.<anonymous> (/opt/outline/node_modules/pg/lib/connection.js:76:21)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
(node:134) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:134) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ConnectionError [SequelizeConnectionError]: The server does not support SSL connections
    at /opt/outline/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:188:20
    at Connection.connectingErrorHandler (/opt/outline/node_modules/pg/lib/client.js:213:14)
    at Connection.emit (events.js:315:20)
    at Connection.EventEmitter.emit (domain.js:483:12)
    at Socket.<anonymous> (/opt/outline/node_modules/pg/lib/connection.js:76:21)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9) {
  parent: Error: The server does not support SSL connections
      at Socket.<anonymous> (/opt/outline/node_modules/pg/lib/connection.js:76:35)
      at Object.onceWrapper (events.js:422:26)
      at Socket.emit (events.js:315:20)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23),
  original: Error: The server does not support SSL connections
      at Socket.<anonymous> (/opt/outline/node_modules/pg/lib/connection.js:76:35)
      at Object.onceWrapper (events.js:422:26)
      at Socket.emit (events.js:315:20)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
}`

Redis Docker
`docker logs c4709efd4800
1:C 06 Sep 2020 09:23:31.635 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 06 Sep 2020 09:23:31.635 # Redis version=6.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 06 Sep 2020 09:23:31.635 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 06 Sep 2020 09:23:31.636 * Running mode=standalone, port=6379.
1:M 06 Sep 2020 09:23:31.636 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 06 Sep 2020 09:23:31.636 # Server initialized
1:M 06 Sep 2020 09:23:31.636 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 06 Sep 2020 09:23:31.636 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 06 Sep 2020 09:23:31.637 * Ready to accept connections
1:M 06 Sep 2020 09:37:40.701 * 100 changes in 300 seconds. Saving...
1:M 06 Sep 2020 09:37:40.701 * Background saving started by pid 17
17:C 06 Sep 2020 09:37:40.705 * DB saved on disk
17:C 06 Sep 2020 09:37:40.705 * RDB: 0 MB of memory used by copy-on-write
1:M 06 Sep 2020 09:37:40.801 * Background saving terminated with success`

I have followed with the Development tutorial of Outline, it's working well.

**Comment by chsasank** [comment]
> (node:134) UnhandledPromiseRejectionWarning: SequelizeConnectionError: The server does not support SSL connections

Something to do with https

**Comment by nguyenrom** [comment]
> > (node:134) UnhandledPromiseRejectionWarning: SequelizeConnectionError: The server does not support SSL connections
> 
> Something to do with https

I have tried with `make https` but it still not working → https://3.1.95.32:4443/
Do you think using Caddy instead of Nginx is a good idea?

**Comment by 8bitgentleman** [comment]
Running into the same issue here

**Comment by MDXDave** [comment]
I already experienced this problem with v0.46.1 and created an issue within the outline repo: https://github.com/outline/outline/issues/1501

They've fixed it in v0.47.0. However you need to add the following line to your `env.outline` file:
`PGSSLMODE=disable`

Additionally, you need to make sure that you using the latest (v0.47.0) docker image. Just pull it by run the following command
`docker pull outlinewiki/outline:latest`
